import { Game } from "@/app/types"

// Single source of truth for the playable game catalog.
//
// IMPORTANT: each `id` here MUST match the route slug handled in
// app/games/[slug]/page.tsx (the `mockGames` keys), because launching a game
// navigates to `/games/${id}`. Keep them in sync.
export const GAMES_CATALOG: Game[] = [
  {
    id: 'monopoly',
    name: 'Monopoly',
    description: 'Buy, sell, and trade properties to become the wealthiest player in this classic board game of economic strategy.',
    image: '/images/monopoly thumbnail.png',
    minPlayers: 2,
    maxPlayers: 6,
    duration: '60-180 min',
    complexity: 'Medium',
    category: ['Strategy', 'Economic'],
  },
  {
    id: 'battleship',
    name: 'Battleship',
    description: 'Strategically place your fleet and take turns firing at your opponent\'s ships in this classic naval combat game.',
    image: '/images/Battleship thumbnail.png',
    minPlayers: 2,
    maxPlayers: 2,
    duration: '15-30 min',
    complexity: 'Easy',
    category: ['Strategy', 'Deduction'],
  },
  {
    id: 'catan',
    name: 'Catan',
    description: 'Collect resources and build settlements in this classic strategy game of trading and development.',
    image: '/images/catan thumbnail.png',
    minPlayers: 3,
    maxPlayers: 4,
    duration: '60-120 min',
    complexity: 'Medium',
    category: ['Strategy', 'Trading'],
  },
  {
    id: 'uno',
    name: 'Uno',
    description: 'Be the first to play all your cards by matching color or number in this fast-paced card game.',
    image: '/images/uno final thumbnail.png',
    minPlayers: 2,
    maxPlayers: 10,
    duration: '15-30 min',
    complexity: 'Easy',
    category: ['Card Game', 'Family'],
  },
  {
    id: 'poker',
    name: 'Poker',
    description: 'Test your luck and bluffing skills in this classic card game of strategy and chance.',
    image: '/images/poker thumbnail.png',
    minPlayers: 2,
    maxPlayers: 10,
    duration: '30-120 min',
    complexity: 'Medium',
    category: ['Card Game', 'Bluffing'],
  },
  {
    id: 'cluedo',
    name: 'Cluedo',
    description: 'Solve the mystery of who committed the murder, with what weapon, and in which room.',
    image: '/images/cluedo thumbnail.png',
    minPlayers: 3,
    maxPlayers: 6,
    duration: '45-60 min',
    complexity: 'Easy',
    category: ['Deduction', 'Mystery'],
  },
  {
    id: 'pictionary',
    name: 'Pictionary',
    description: 'Draw clues for your team to guess in this classic drawing and guessing game.',
    image: '/images/pictionary thumbnail.png',
    minPlayers: 4,
    maxPlayers: 8,
    duration: '30-60 min',
    complexity: 'Easy',
    category: ['Party', 'Drawing'],
  },
  {
    id: 'scribbleio',
    name: 'Scribble.io',
    description: 'Draw and guess drawings in this fun online multiplayer game where creativity meets competition.',
    image: '/images/scribbleio thumbnail.png',
    minPlayers: 2,
    maxPlayers: 12,
    duration: '10-30 min',
    complexity: 'Easy',
    category: ['Online', 'Drawing'],
  },
  {
    id: 'codenames',
    name: 'Codenames',
    description: 'Give one-word clues to help your team identify agents while avoiding the assassin.',
    image: '/images/codenames thumbnal.png',
    minPlayers: 4,
    maxPlayers: 8,
    duration: '15-30 min',
    complexity: 'Easy',
    category: ['Party', 'Word Game'],
  },
  {
    id: 'terramystica',
    name: 'Terra Mystica',
    description: 'Shape the land and develop your civilization in this deep strategy game.',
    image: '/images/terra mystica thumbnail.png',
    minPlayers: 2,
    maxPlayers: 5,
    duration: '60-150 min',
    complexity: 'Hard',
    category: ['Strategy', 'Eurogame'],
  },
  {
    id: '7wonders',
    name: '7 Wonders',
    description: 'Lead an ancient civilization as it rises from its barbaric roots to become a world power.',
    image: '/images/7wonders thumbnail.png',
    minPlayers: 3,
    maxPlayers: 7,
    duration: '30 min',
    complexity: 'Medium',
    category: ['Strategy', 'Card Game'],
  },
]

export function getGameById(id: string | null | undefined): Game | undefined {
  if (!id) return undefined
  return GAMES_CATALOG.find((g) => g.id === id)
}
